from transformers import AutoTokenizer, LlamaForCausalLM, BitsAndBytesConfig
from tqdm import tqdm
import torch
from optimum.bettertransformer import BetterTransformer

# initialize the model
#bnb_4bit_quant_type="nf4"
bnb_config = BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.float16,
            bnb_4bit_use_double_quant=True,
            llm_int8_enable_fp32_cpu_offload=True,
            )

layer_group = ["transformer.word_embeddings",
    "transformer.word_embeddings_layernorm",
    "model.embed_tokens.weight",
    "model.layers.0.self_attn.q_proj.weight",
    "model.layers.0.self_attn.k_proj.weight",
    "model.layers.0.self_attn.v_proj.weight",
    "model.layers.0.self_attn.o_proj.weight",
    "model.layers.0.mlp.gate_proj.weight",
    "model.layers.0.mlp.up_proj.weight",
    "model.layers.0.mlp.down_proj.weight",
    "model.layers.0.input_layernorm.weight",
    "model.layers.0.post_attention_layernorm.weight"]
layer_group1 = ["model.layers.1.self_attn.q_proj.weight",
    "model.layers.1.self_attn.k_proj.weight",
    "model.layers.1.self_attn.v_proj.weight",
    "model.layers.1.self_attn.o_proj.weight",
    "model.layers.1.mlp.gate_proj.weight",
    "model.layers.1.mlp.up_proj.weight",
    "model.layers.1.mlp.down_proj.weight",
    "model.layers.1.input_layernorm.weight",
    "model.layers.1.post_attention_layernorm.weight"]
layer_group2 = ["model.layers.2.self_attn.q_proj.weight",
    "model.layers.2.self_attn.k_proj.weight",
    "model.layers.2.self_attn.v_proj.weight",
    "model.layers.2.self_attn.o_proj.weight",
    "model.layers.2.mlp.gate_proj.weight",
    "model.layers.2.mlp.up_proj.weight",
    "model.layers.2.mlp.down_proj.weight",
    "model.layers.2.input_layernorm.weight",
    "model.layers.2.post_attention_layernorm.weight"]
layer_group3 = ["model.layers.3.self_attn.q_proj.weight",
    "model.layers.3.self_attn.k_proj.weight",
    "model.layers.3.self_attn.v_proj.weight",
    "model.layers.3.self_attn.o_proj.weight",
    "model.layers.3.mlp.gate_proj.weight",
    "model.layers.3.mlp.up_proj.weight",
    "model.layers.3.mlp.down_proj.weight",
    "model.layers.3.input_layernorm.weight",
    "model.layers.3.post_attention_layernorm.weight"]
layer_group4 = ["model.layers.4.self_attn.q_proj.weight",
    "model.layers.4.self_attn.k_proj.weight",
    "model.layers.4.self_attn.v_proj.weight",
    "model.layers.4.self_attn.o_proj.weight",
    "model.layers.4.mlp.gate_proj.weight",
    "model.layers.4.mlp.up_proj.weight",
    "model.layers.4.mlp.down_proj.weight",
    "model.layers.4.input_layernorm.weight",
    "model.layers.4.post_attention_layernorm.weight"]
layer_group5 = ["model.layers.5.self_attn.q_proj.weight",
    "model.layers.5.self_attn.k_proj.weight",
    "model.layers.5.self_attn.v_proj.weight",
    "model.layers.5.self_attn.o_proj.weight",
    "model.layers.5.mlp.gate_proj.weight",
    "model.layers.5.mlp.up_proj.weight",
    "model.layers.5.mlp.down_proj.weight",
    "model.layers.5.input_layernorm.weight",
    "model.layers.5.post_attention_layernorm.weight"]
layer_group6 = ["model.layers.6.self_attn.q_proj.weight",
    "model.layers.6.self_attn.k_proj.weight",
    "model.layers.6.self_attn.v_proj.weight",
    "model.layers.6.self_attn.o_proj.weight",
    "model.layers.6.mlp.gate_proj.weight",
    "model.layers.6.mlp.up_proj.weight",
    "model.layers.6.mlp.down_proj.weight",
    "model.layers.6.input_layernorm.weight",
    "model.layers.6.post_attention_layernorm.weight"]
layer_group7 = ["model.layers.7.self_attn.q_proj.weight",
    "model.layers.7.self_attn.k_proj.weight",
    "model.layers.7.self_attn.v_proj.weight",
    "model.layers.7.self_attn.o_proj.weight",
    "model.layers.7.mlp.gate_proj.weight",
    "model.layers.7.mlp.up_proj.weight",
    "model.layers.7.mlp.down_proj.weight",
    "model.layers.7.input_layernorm.weight",
    "model.layers.7.post_attention_layernorm.weight"]
layer_group8 = ["model.layers.8.self_attn.q_proj.weight",
    "model.layers.8.self_attn.k_proj.weight",
    "model.layers.8.self_attn.v_proj.weight",
    "model.layers.8.self_attn.o_proj.weight",
    "model.layers.8.mlp.gate_proj.weight",
    "model.layers.8.mlp.up_proj.weight",
    "model.layers.8.mlp.down_proj.weight",
    "model.layers.8.input_layernorm.weight",
    "model.layers.8.post_attention_layernorm.weight"]
layer_group9 = ["model.layers.9.self_attn.q_proj.weight",
    "model.layers.9.self_attn.k_proj.weight",
    "model.layers.9.self_attn.v_proj.weight",
    "model.layers.9.self_attn.o_proj.weight",
    "model.layers.9.mlp.gate_proj.weight",
    "model.layers.9.mlp.up_proj.weight",
    "model.layers.9.mlp.down_proj.weight",
    "model.layers.9.input_layernorm.weight",
    "model.layers.9.post_attention_layernorm.weight"]
layer_group10 = ["model.layers.10.self_attn.q_proj.weight",
    "model.layers.10.self_attn.k_proj.weight",
    "model.layers.10.self_attn.v_proj.weight",
    "model.layers.10.self_attn.o_proj.weight",
    "model.layers.10.mlp.gate_proj.weight",
    "model.layers.10.mlp.up_proj.weight",
    "model.layers.10.mlp.down_proj.weight",
    "model.layers.10.input_layernorm.weight",
    "model.layers.10.post_attention_layernorm.weight"]
layer_group11 = ["model.layers.11.self_attn.q_proj.weight",
    "model.layers.11.self_attn.k_proj.weight",
    "model.layers.11.self_attn.v_proj.weight",
    "model.layers.11.self_attn.o_proj.weight",
    "model.layers.11.mlp.gate_proj.weight",
    "model.layers.11.mlp.up_proj.weight",
    "model.layers.11.mlp.down_proj.weight",
    "model.layers.11.input_layernorm.weight",
    "model.layers.11.post_attention_layernorm.weight"]
layer_group12 = ["model.layers.12.self_attn.q_proj.weight",
    "model.layers.12.self_attn.k_proj.weight",
    "model.layers.12.self_attn.v_proj.weight",
    "model.layers.12.self_attn.o_proj.weight",
    "model.layers.12.mlp.gate_proj.weight",
    "model.layers.12.mlp.up_proj.weight",
    "model.layers.12.mlp.down_proj.weight",
    "model.layers.12.input_layernorm.weight",
    "model.layers.12.post_attention_layernorm.weight"]
layer_group13 = ["model.layers.13.self_attn.q_proj.weight",
    "model.layers.13.self_attn.k_proj.weight",
    "model.layers.13.self_attn.v_proj.weight",
    "model.layers.13.self_attn.o_proj.weight",
    "model.layers.13.mlp.gate_proj.weight",
    "model.layers.13.mlp.up_proj.weight",
    "model.layers.13.mlp.down_proj.weight",
    "model.layers.13.input_layernorm.weight",
    "model.layers.13.post_attention_layernorm.weight"]
layer_group14 = ["model.layers.14.self_attn.q_proj.weight",
    "model.layers.14.self_attn.k_proj.weight",
    "model.layers.14.self_attn.v_proj.weight",
    "model.layers.14.self_attn.o_proj.weight",
    "model.layers.14.mlp.gate_proj.weight",
    "model.layers.14.mlp.up_proj.weight",
    "model.layers.14.mlp.down_proj.weight",
    "model.layers.14.input_layernorm.weight",
    "model.layers.14.post_attention_layernorm.weight"]
layer_group15 = ["model.layers.15.self_attn.q_proj.weight",
    "model.layers.15.self_attn.k_proj.weight",
    "model.layers.15.self_attn.v_proj.weight",
    "model.layers.15.self_attn.o_proj.weight",
    "model.layers.15.mlp.gate_proj.weight",
    "model.layers.15.mlp.up_proj.weight",
    "model.layers.15.mlp.down_proj.weight",
    "model.layers.15.input_layernorm.weight",
    "model.layers.15.post_attention_layernorm.weight"]
layer_group16 = ["model.layers.16.self_attn.q_proj.weight",
    "model.layers.16.self_attn.k_proj.weight",
    "model.layers.16.self_attn.v_proj.weight",
    "model.layers.16.self_attn.o_proj.weight",
    "model.layers.16.mlp.gate_proj.weight",
    "model.layers.16.mlp.up_proj.weight",
    "model.layers.16.mlp.down_proj.weight",
    "model.layers.16.input_layernorm.weight",
    "model.layers.16.post_attention_layernorm.weight"]
layer_group17 = ["model.layers.17.self_attn.q_proj.weight",
    "model.layers.17.self_attn.k_proj.weight",
    "model.layers.17.self_attn.v_proj.weight",
    "model.layers.17.self_attn.o_proj.weight",
    "model.layers.17.mlp.gate_proj.weight",
    "model.layers.17.mlp.up_proj.weight",
    "model.layers.17.mlp.down_proj.weight",
    "model.layers.17.input_layernorm.weight",
    "model.layers.17.post_attention_layernorm.weight"]
layer_group18 = ["model.layers.18.self_attn.q_proj.weight",
    "model.layers.18.self_attn.k_proj.weight",
    "model.layers.18.self_attn.v_proj.weight",
    "model.layers.18.self_attn.o_proj.weight",
    "model.layers.18.mlp.gate_proj.weight",
    "model.layers.18.mlp.up_proj.weight",
    "model.layers.18.mlp.down_proj.weight",
    "model.layers.18.input_layernorm.weight",
    "model.layers.18.post_attention_layernorm.weight"]
layer_group19 = ["model.layers.19.self_attn.q_proj.weight",
    "model.layers.19.self_attn.k_proj.weight",
    "model.layers.19.self_attn.v_proj.weight",
    "model.layers.19.self_attn.o_proj.weight",
    "model.layers.19.mlp.gate_proj.weight",
    "model.layers.19.mlp.up_proj.weight",
    "model.layers.19.mlp.down_proj.weight",
    "model.layers.19.input_layernorm.weight",
    "model.layers.19.post_attention_layernorm.weight"]
layer_group20 = ["model.layers.20.self_attn.q_proj.weight",
    "model.layers.20.self_attn.k_proj.weight",
    "model.layers.20.self_attn.v_proj.weight",
    "model.layers.20.self_attn.o_proj.weight",
    "model.layers.20.mlp.gate_proj.weight",
    "model.layers.20.mlp.up_proj.weight",
    "model.layers.20.mlp.down_proj.weight",
    "model.layers.20.input_layernorm.weight",
    "model.layers.20.post_attention_layernorm.weight"]
layer_group21 = ["model.layers.21.self_attn.q_proj.weight",
    "model.layers.21.self_attn.k_proj.weight",
    "model.layers.21.self_attn.v_proj.weight",
    "model.layers.21.self_attn.o_proj.weight",
    "model.layers.21.mlp.gate_proj.weight",
    "model.layers.21.mlp.up_proj.weight",
    "model.layers.21.mlp.down_proj.weight",
    "model.layers.21.input_layernorm.weight",
    "model.layers.21.post_attention_layernorm.weight"]
layer_group22 = ["model.layers.22.self_attn.q_proj.weight",
    "model.layers.22.self_attn.k_proj.weight",
    "model.layers.22.self_attn.v_proj.weight",
    "model.layers.22.self_attn.o_proj.weight",
    "model.layers.22.mlp.gate_proj.weight",
    "model.layers.22.mlp.up_proj.weight",
    "model.layers.22.mlp.down_proj.weight",
    "model.layers.22.input_layernorm.weight",
    "model.layers.22.post_attention_layernorm.weight"]
layer_group23 = ["model.layers.23.self_attn.q_proj.weight",
    "model.layers.23.self_attn.k_proj.weight",
    "model.layers.23.self_attn.v_proj.weight",
    "model.layers.23.self_attn.o_proj.weight",
    "model.layers.23.mlp.gate_proj.weight",
    "model.layers.23.mlp.up_proj.weight",
    "model.layers.23.mlp.down_proj.weight",
    "model.layers.23.input_layernorm.weight",
    "model.layers.23.post_attention_layernorm.weight"]
layer_group24 = ["model.layers.24.self_attn.q_proj.weight",
    "model.layers.24.self_attn.k_proj.weight",
    "model.layers.24.self_attn.v_proj.weight",
    "model.layers.24.self_attn.o_proj.weight",
    "model.layers.24.mlp.gate_proj.weight",
    "model.layers.24.mlp.up_proj.weight",
    "model.layers.24.mlp.down_proj.weight",
    "model.layers.24.input_layernorm.weight",
    "model.layers.24.post_attention_layernorm.weight"]
layer_group25 = ["model.layers.25.self_attn.q_proj.weight",
    "model.layers.25.self_attn.k_proj.weight",
    "model.layers.25.self_attn.v_proj.weight",
    "model.layers.25.self_attn.o_proj.weight",
    "model.layers.25.mlp.gate_proj.weight",
    "model.layers.25.mlp.up_proj.weight",
    "model.layers.25.mlp.down_proj.weight",
    "model.layers.25.input_layernorm.weight",
    "model.layers.25.post_attention_layernorm.weight"]
layer_group26 = ["model.layers.26.self_attn.q_proj.weight",
    "model.layers.26.self_attn.k_proj.weight",
    "model.layers.26.self_attn.v_proj.weight",
    "model.layers.26.self_attn.o_proj.weight",
    "model.layers.26.mlp.gate_proj.weight",
    "model.layers.26.mlp.up_proj.weight",
    "model.layers.26.mlp.down_proj.weight",
    "model.layers.26.input_layernorm.weight",
    "model.layers.26.post_attention_layernorm.weight"]
layer_group27 = ["model.layers.27.self_attn.q_proj.weight",
    "model.layers.27.self_attn.k_proj.weight",
    "model.layers.27.self_attn.v_proj.weight",
    "model.layers.27.self_attn.o_proj.weight",
    "model.layers.27.mlp.gate_proj.weight",
    "model.layers.27.mlp.up_proj.weight",
    "model.layers.27.mlp.down_proj.weight",
    "model.layers.27.input_layernorm.weight",
    "model.layers.27.post_attention_layernorm.weight"]
layer_group28 = ["model.layers.28.self_attn.q_proj.weight",
    "model.layers.28.self_attn.k_proj.weight",
    "model.layers.28.self_attn.v_proj.weight",
    "model.layers.28.self_attn.o_proj.weight",
    "model.layers.28.mlp.gate_proj.weight",
    "model.layers.28.mlp.up_proj.weight",
    "model.layers.28.mlp.down_proj.weight",
    "model.layers.28.input_layernorm.weight",
    "model.layers.28.post_attention_layernorm.weight"]
layer_group29 = ["model.layers.29.self_attn.q_proj.weight",
    "model.layers.29.self_attn.k_proj.weight",
    "model.layers.29.self_attn.v_proj.weight",
    "model.layers.29.self_attn.o_proj.weight",
    "model.layers.29.mlp.gate_proj.weight",
    "model.layers.29.mlp.up_proj.weight",
    "model.layers.29.mlp.down_proj.weight",
    "model.layers.29.input_layernorm.weight",
    "model.layers.29.post_attention_layernorm.weight"]
layer_group30 = ["model.layers.30.self_attn.q_proj.weight",
    "model.layers.30.self_attn.k_proj.weight",
    "model.layers.30.self_attn.v_proj.weight",
    "model.layers.30.self_attn.o_proj.weight",
    "model.layers.30.mlp.gate_proj.weight",
    "model.layers.30.mlp.up_proj.weight",
    "model.layers.30.mlp.down_proj.weight",
    "model.layers.30.input_layernorm.weight",
    "model.layers.30.post_attention_layernorm.weight"]
layer_group31 = ["model.layers.31.self_attn.q_proj.weight",
    "model.layers.31.self_attn.k_proj.weight",
    "model.layers.31.self_attn.v_proj.weight",
    "model.layers.31.self_attn.o_proj.weight",
    "model.layers.31.mlp.gate_proj.weight",
    "model.layers.31.mlp.up_proj.weight",
    "model.layers.31.mlp.down_proj.weight",
    "model.layers.31.input_layernorm.weight",
    "model.layers.31.post_attention_layernorm.weight"]
layer_group32 = ["model.layers.32.self_attn.q_proj.weight",
    "model.layers.32.self_attn.k_proj.weight",
    "model.layers.32.self_attn.v_proj.weight",
    "model.layers.32.self_attn.o_proj.weight",
    "model.layers.32.mlp.gate_proj.weight",
    "model.layers.32.mlp.up_proj.weight",
    "model.layers.32.mlp.down_proj.weight",
    "model.layers.32.input_layernorm.weight",
    "model.layers.32.post_attention_layernorm.weight"]
layer_group33 = ["model.layers.33.self_attn.q_proj.weight",
    "model.layers.33.self_attn.k_proj.weight",
    "model.layers.33.self_attn.v_proj.weight",
    "model.layers.33.self_attn.o_proj.weight",
    "model.layers.33.mlp.gate_proj.weight",
    "model.layers.33.mlp.up_proj.weight",
    "model.layers.33.mlp.down_proj.weight",
    "model.layers.33.input_layernorm.weight",
    "model.layers.33.post_attention_layernorm.weight"]
layer_group34 = ["model.layers.34.self_attn.q_proj.weight",
    "model.layers.34.self_attn.k_proj.weight",
    "model.layers.34.self_attn.v_proj.weight",
    "model.layers.34.self_attn.o_proj.weight",
    "model.layers.34.mlp.gate_proj.weight",
    "model.layers.34.mlp.up_proj.weight",
    "model.layers.34.mlp.down_proj.weight",
    "model.layers.34.input_layernorm.weight",
    "model.layers.34.post_attention_layernorm.weight"]
layer_group35 = ["model.layers.35.self_attn.q_proj.weight",
    "model.layers.35.self_attn.k_proj.weight",
    "model.layers.35.self_attn.v_proj.weight",
    "model.layers.35.self_attn.o_proj.weight",
    "model.layers.35.mlp.gate_proj.weight",
    "model.layers.35.mlp.up_proj.weight",
    "model.layers.35.mlp.down_proj.weight",
    "model.layers.35.input_layernorm.weight",
    "model.layers.35.post_attention_layernorm.weight"]
layer_group36 = ["model.layers.36.self_attn.q_proj.weight",
    "model.layers.36.self_attn.k_proj.weight",
    "model.layers.36.self_attn.v_proj.weight",
    "model.layers.36.self_attn.o_proj.weight",
    "model.layers.36.mlp.gate_proj.weight",
    "model.layers.36.mlp.up_proj.weight",
    "model.layers.36.mlp.down_proj.weight",
    "model.layers.36.input_layernorm.weight",
    "model.layers.36.post_attention_layernorm.weight"]
layer_group37 = ["model.layers.37.self_attn.q_proj.weight",
    "model.layers.37.self_attn.k_proj.weight",
    "model.layers.37.self_attn.v_proj.weight",
    "model.layers.37.self_attn.o_proj.weight",
    "model.layers.37.mlp.gate_proj.weight",
    "model.layers.37.mlp.up_proj.weight",
    "model.layers.37.mlp.down_proj.weight",
    "model.layers.37.input_layernorm.weight",
    "model.layers.37.post_attention_layernorm.weight"]
layer_group38 = ["model.layers.38.self_attn.q_proj.weight",
    "model.layers.38.self_attn.k_proj.weight",
    "model.layers.38.self_attn.v_proj.weight",
    "model.layers.38.self_attn.o_proj.weight",
    "model.layers.38.mlp.gate_proj.weight",
    "model.layers.38.mlp.up_proj.weight",
    "model.layers.38.mlp.down_proj.weight",
    "model.layers.38.input_layernorm.weight",
    "model.layers.38.post_attention_layernorm.weight"]
layer_group39 = ["model.layers.39.self_attn.q_proj.weight",
    "model.layers.39.self_attn.k_proj.weight",
    "model.layers.39.self_attn.v_proj.weight",
    "model.layers.39.self_attn.o_proj.weight",
    "model.layers.39.mlp.gate_proj.weight",
    "model.layers.39.mlp.up_proj.weight",
    "model.layers.39.mlp.down_proj.weight",
    "model.layers.39.input_layernorm.weight",
    "model.layers.39.post_attention_layernorm.weight"]
layer_group40 = ["model.layers.40.self_attn.q_proj.weight",
    "model.layers.40.self_attn.k_proj.weight",
    "model.layers.40.self_attn.v_proj.weight",
    "model.layers.40.self_attn.o_proj.weight",
    "model.layers.40.mlp.gate_proj.weight",
    "model.layers.40.mlp.up_proj.weight",
    "model.layers.40.mlp.down_proj.weight",
    "model.layers.40.input_layernorm.weight",
    "model.layers.40.post_attention_layernorm.weight"]
layer_group41 = ["model.layers.41.self_attn.q_proj.weight",
    "model.layers.41.self_attn.k_proj.weight",
    "model.layers.41.self_attn.v_proj.weight",
    "model.layers.41.self_attn.o_proj.weight",
    "model.layers.41.mlp.gate_proj.weight",
    "model.layers.41.mlp.up_proj.weight",
    "model.layers.41.mlp.down_proj.weight",
    "model.layers.41.input_layernorm.weight",
    "model.layers.41.post_attention_layernorm.weight"]
layer_group42 = ["model.layers.42.self_attn.q_proj.weight",
    "model.layers.42.self_attn.k_proj.weight",
    "model.layers.42.self_attn.v_proj.weight",
    "model.layers.42.self_attn.o_proj.weight",
    "model.layers.42.mlp.gate_proj.weight",
    "model.layers.42.mlp.up_proj.weight",
    "model.layers.42.mlp.down_proj.weight",
    "model.layers.42.input_layernorm.weight",
    "model.layers.42.post_attention_layernorm.weight"]
layer_group43 = ["model.layers.43.self_attn.q_proj.weight",
    "model.layers.43.self_attn.k_proj.weight",
    "model.layers.43.self_attn.v_proj.weight",
    "model.layers.43.self_attn.o_proj.weight",
    "model.layers.43.mlp.gate_proj.weight",
    "model.layers.43.mlp.up_proj.weight",
    "model.layers.43.mlp.down_proj.weight",
    "model.layers.43.input_layernorm.weight",
    "model.layers.43.post_attention_layernorm.weight"]
layer_group44 = ["model.layers.44.self_attn.q_proj.weight",
    "model.layers.44.self_attn.k_proj.weight",
    "model.layers.44.self_attn.v_proj.weight",
    "model.layers.44.self_attn.o_proj.weight",
    "model.layers.44.mlp.gate_proj.weight",
    "model.layers.44.mlp.up_proj.weight",
    "model.layers.44.mlp.down_proj.weight",
    "model.layers.44.input_layernorm.weight",
    "model.layers.44.post_attention_layernorm.weight"]
layer_group45 = ["model.layers.45.self_attn.q_proj.weight",
    "model.layers.45.self_attn.k_proj.weight",
    "model.layers.45.self_attn.v_proj.weight",
    "model.layers.45.self_attn.o_proj.weight",
    "model.layers.45.mlp.gate_proj.weight",
    "model.layers.45.mlp.up_proj.weight",
    "model.layers.45.mlp.down_proj.weight",
    "model.layers.45.input_layernorm.weight",
    "model.layers.45.post_attention_layernorm.weight"]
layer_group46 = ["model.layers.46.self_attn.q_proj.weight",
    "model.layers.46.self_attn.k_proj.weight",
    "model.layers.46.self_attn.v_proj.weight",
    "model.layers.46.self_attn.o_proj.weight",
    "model.layers.46.mlp.gate_proj.weight",
    "model.layers.46.mlp.up_proj.weight",
    "model.layers.46.mlp.down_proj.weight",
    "model.layers.46.input_layernorm.weight",
    "model.layers.46.post_attention_layernorm.weight"]
layer_group47 = ["model.layers.47.self_attn.q_proj.weight",
    "model.layers.47.self_attn.k_proj.weight",
    "model.layers.47.self_attn.v_proj.weight",
    "model.layers.47.self_attn.o_proj.weight",
    "model.layers.47.mlp.gate_proj.weight",
    "model.layers.47.mlp.up_proj.weight",
    "model.layers.47.mlp.down_proj.weight",
    "model.layers.47.input_layernorm.weight",
    "model.layers.47.post_attention_layernorm.weight"]
layer_group48 = ["model.layers.48.self_attn.q_proj.weight",
    "model.layers.48.self_attn.k_proj.weight",
    "model.layers.48.self_attn.v_proj.weight",
    "model.layers.48.self_attn.o_proj.weight",
    "model.layers.48.mlp.gate_proj.weight",
    "model.layers.48.mlp.up_proj.weight",
    "model.layers.48.mlp.down_proj.weight",
    "model.layers.48.input_layernorm.weight",
    "model.layers.48.post_attention_layernorm.weight"]
layer_group49 = ["model.layers.49.self_attn.q_proj.weight",
    "model.layers.49.self_attn.k_proj.weight",
    "model.layers.49.self_attn.v_proj.weight",
    "model.layers.49.self_attn.o_proj.weight",
    "model.layers.49.mlp.gate_proj.weight",
    "model.layers.49.mlp.up_proj.weight",
    "model.layers.49.mlp.down_proj.weight",
    "model.layers.49.input_layernorm.weight",
    "model.layers.49.post_attention_layernorm.weight"]

device_map = {
    **{layer: 0 for layer in layer_group},
    **{layer: 0 for layer in layer_group1},
    **{layer: 0 for layer in layer_group2},
    **{layer: 0 for layer in layer_group3},
    **{layer: 0 for layer in layer_group4},
    **{layer: 0 for layer in layer_group5},
    **{layer: 0 for layer in layer_group6},
    **{layer: 0 for layer in layer_group7},
    **{layer: 0 for layer in layer_group8},
    **{layer: 0 for layer in layer_group9},
    **{layer: 0 for layer in layer_group10},
    **{layer: 0 for layer in layer_group11},
    **{layer: 0 for layer in layer_group12},
    **{layer: 0 for layer in layer_group13},
    **{layer: 0 for layer in layer_group14},
    **{layer: 0 for layer in layer_group15},
    **{layer: 0 for layer in layer_group16},
    **{layer: 0 for layer in layer_group17},
    **{layer: 0 for layer in layer_group18},
    **{layer: 0 for layer in layer_group19},
    **{layer: 0 for layer in layer_group20},
    **{layer: 0 for layer in layer_group21},
    **{layer: 0 for layer in layer_group22},
    **{layer: 0 for layer in layer_group23},
    **{layer: 0 for layer in layer_group24},
    **{layer: 0 for layer in layer_group25},
    **{layer: 0 for layer in layer_group26},
    **{layer: 0 for layer in layer_group27},
    **{layer: 0 for layer in layer_group28},
    **{layer: 0 for layer in layer_group29},
    **{layer: 0 for layer in layer_group30},
    **{layer: 0 for layer in layer_group31},
    **{layer: 0 for layer in layer_group32},
    **{layer: 0 for layer in layer_group33},
    **{layer: 0 for layer in layer_group34},
    **{layer: 0 for layer in layer_group35},
    **{layer: 0 for layer in layer_group36},
    **{layer: 0 for layer in layer_group37},
    **{layer: 0 for layer in layer_group38},
    **{layer: 0 for layer in layer_group39},
    **{layer: 0 for layer in layer_group40},
    **{layer: 0 for layer in layer_group41},
    **{layer: 0 for layer in layer_group42},
    **{layer: 0 for layer in layer_group43},
    **{layer: 0 for layer in layer_group44},
    **{layer: 0 for layer in layer_group45},
    **{layer: 0 for layer in layer_group46},
    **{layer: 0 for layer in layer_group47},
    **{layer: 0 for layer in layer_group48},
    **{layer: 0 for layer in layer_group49},
    "model.norm.weight": 0,
    "lm_head": "cpu",
    "transformer.h": 0,
    "transformer.ln_f": 0,
    "position_ids": "cpu",
}

model_path = "Phind/Phind-CodeLlama-34B-v2"
model = LlamaForCausalLM.from_pretrained(model_path, quantization_config=bnb_config, device_map=device_map)
bt_model = BetterTransformer.transform(model, keep_original_model=False)
tokenizer = AutoTokenizer.from_pretrained(model_path)
#model.config.quantization_config.to_dict()

# HumanEval helper

def generate(prompt: str):
    
    tokenizer.pad_token = tokenizer.eos_token
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, max_length=4096)

    with torch.backends.cuda.sdp_kernel(enable_flash=True, enable_math=False, enable_mem_efficient=False):
        # Generate
        generate_ids = bt_model.generate(inputs.input_ids.to("cuda"),do_sample=True, max_length=4096, temperature=0.7)
        completion = tokenizer.batch_decode(generate_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
        completion = completion.replace(prompt, "").split("\n\n\n")[0]

        # Print the completion to the console
        print("Generated Completion:")
        print(completion)

        return completion
prompt = "Please write a small script that prints the numbers 1-10 in the console"
generated_text = generate(prompt)
